// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package emsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       int32
	Email    string
	Password string
	Name     string
	Age      pgtype.Numeric
	Isactive pgtype.Bool
	Created  pgtype.Timestamp
	Img      pgtype.Text
}
